### ISSUE TITLE
Millions of errors when build with rusticata 

### ISSUE THREAD

**Issue by copslock** [rusticata/ipsec-parser#3]
When build rusticata,got a lot of mismatched types errors, and the openvpn repo complain about cannot find 0.5.0 version rusticata-marcos

RUST is a goot language,but i didn't feel any convinient

**Comment by copslock** [comment]
warning: unused `#[macro_use]` import
 --> src/lib.rs:3:1
  |
3 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::str`
 --> src/ssh.rs:1:5
  |
1 | use std::str;
  |     ^^^^^^^^

warning: unused import: `str`
  --> src/tls.rs:16:15
   |
16 | use std::{mem,str};
   |               ^^^

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
  --> src/ipsec.rs:34:13
   |
34 |             IResult::Done(rem,ref hdr) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
  --> src/ipsec.rs:40:21
   |
40 |                     IResult::Done(_,ref p) => {
   |                     ^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no function or associated item named `from_u16` found for type `ipsec_parser::IkeTransformDHType` in the current scope
  --> src/ipsec.rs:50:53
   |
50 |                                     self.dh_group = IkeTransformDHType::from_u16(kex.dh_group);
   |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformDHType`

error[E0277]: `ipsec_parser::IkeTransformDHType` doesn't implement `std::fmt::Display`
  --> src/ipsec.rs:52:59
   |
52 |                                     debug!("KEX {}/{:?}", kex.dh_group, self.dh_group);
   |                                                           ^^^^^^^^^^^^ `ipsec_parser::IkeTransformDHType` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `ipsec_parser::IkeTransformDHType`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: required by `std::fmt::Display::fmt`

error[E0599]: no function or associated item named `from_u8` found for type `ipsec_parser::IkeTransformType` in the current scope
  --> src/ipsec.rs:85:27
   |
85 |                 let xty = IkeTransformType::from_u8(xform.transform_type);
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformType`

error[E0277]: `ipsec_parser::IkeTransformType` doesn't implement `std::fmt::Display`
  --> src/ipsec.rs:86:48
   |
86 |                 debug!("\ttype: {:?} / {}",xty,xform.transform_type);
   |                                                ^^^^^^^^^^^^^^^^^^^^ `ipsec_parser::IkeTransformType` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `ipsec_parser::IkeTransformType`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: required by `std::fmt::Display::fmt`

error[E0599]: no function or associated item named `from_u16` found for type `ipsec_parser::IkeTransformEncType` in the current scope
  --> src/ipsec.rs:89:62
   |
89 |                         debug!("\tEncryptionAlgorithm: {:?}",IkeTransformEncType::from_u16(xform.transform_id));
   |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformEncType`

error[E0599]: no function or associated item named `from_u16` found for type `ipsec_parser::IkeTransformPRFType` in the current scope
  --> src/ipsec.rs:92:63
   |
92 |                         debug!("\tPseudoRandomFunction: {:?}",IkeTransformPRFType::from_u16(xform.transform_id));
   |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformPRFType`

error[E0599]: no function or associated item named `from_u16` found for type `ipsec_parser::IkeTransformAuthType` in the current scope
  --> src/ipsec.rs:95:61
   |
95 |                         debug!("\tIntegrityAlgorithm: {:?}",IkeTransformAuthType::from_u16(xform.transform_id));
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformAuthType`

error[E0599]: no function or associated item named `from_u16` found for type `ipsec_parser::IkeTransformDHType` in the current scope
  --> src/ipsec.rs:98:61
   |
98 |                         debug!("\tDiffieHellmanGroup: {:?}",IkeTransformDHType::from_u16(xform.transform_id));
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformDHType`

error[E0599]: no function or associated item named `from_u16` found for type `ipsec_parser::IkeTransformESNType` in the current scope
   --> src/ipsec.rs:101:66
    |
101 |                         debug!("\tExtendedSequenceNumbers: {:?}",IkeTransformESNType::from_u16(xform.transform_id));
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformESNType`

error[E0277]: `ipsec_parser::IkeTransformType` doesn't implement `std::fmt::Display`
   --> src/ipsec.rs:103:62
    |
103 |                     _ => warn!("\tUnknown transform type {}",xform.transform_type),
    |                                                              ^^^^^^^^^^^^^^^^^^^^ `ipsec_parser::IkeTransformType` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `ipsec_parser::IkeTransformType`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: required by `std::fmt::Display::fmt`

error[E0599]: no function or associated item named `from_u8` found for type `ipsec_parser::IkeTransformType` in the current scope
   --> src/ipsec.rs:117:27
    |
117 |                 let xty = IkeTransformType::from_u8(xform.transform_type);
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `ipsec_parser::IkeTransformType`

error[E0599]: no associated item named `None` found for type `ipsec_parser::IkeTransformAuthType` in the current scope
   --> src/ipsec.rs:127:52
    |
127 |             if prop_int.len() == 0 { prop_int.push(IkeTransformAuthType::None as u16); }
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ associated item not found in `ipsec_parser::IkeTransformAuthType`

error[E0605]: non-primitive cast: `ipsec_parser::IkeTransformDHType` as `u16`
   --> src/ipsec.rs:128:52
    |
128 |             if prop_dhg.len() == 0 { prop_int.push(IkeTransformDHType::None as u16); }
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait

error[E0605]: non-primitive cast: `ipsec_parser::IkeTransformESNType` as `u16`
   --> src/ipsec.rs:129:52
    |
129 |             if prop_esn.len() == 0 { prop_esn.push(IkeTransformESNType::NoESN as u16); }
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
  --> src/ntp.rs:20:13
   |
20 |             IResult::Done(rem,ref res) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
  --> src/ssh.rs:36:13
   |
36 |             IResult::Done(rem,(ref crap, ref res)) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0609]: no field `proto` on type `&_`
  --> src/ssh.rs:52:43
   |
52 |                 info!("protocol\n{}", res.proto.to_hex(16));
   |                                           ^^^^^

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
  --> src/ssh.rs:82:13
   |
82 |             IResult::Done(rem,ref res) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Incomplete` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
  --> src/ssh.rs:85:13
   |
85 |             IResult::Incomplete(_e) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:131:30
    |
131 |                             &IResult::Done(_,ref l) => {
    |                              ^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:249:13
    |
249 |             IResult::Done(rem2,ref msg_list) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Incomplete` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:259:13
    |
259 |             IResult::Incomplete(_) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Error` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:264:13
    |
264 |             IResult::Error(e) => { warn!("parse_tls_record_with_header failed: {:?}",e); status |= R_STATUS_FAIL; },
    |             ^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:300:17
    |
300 |                 IResult::Done(rem, ref r) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Incomplete` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:305:17
    |
305 |                 IResult::Incomplete(_) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Error` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:310:17
    |
310 |                 IResult::Error(e) => { warn!("Parsing failed: {:?}",e); break },
    |                 ^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:465:17
    |
465 |                 IResult::Done(_,ref parsed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:489:17
    |
489 |                 IResult::Done(_,ref parsed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error[E0599]: no variant named `Done` found for type `std::result::Result<(_, _), nom::Err<_, _>>` in the current scope
   --> src/tls.rs:501:17
    |
501 |                 IResult::Done(_,ref parsed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `std::result::Result<(_, _), nom::Err<_, _>>`

error: aborting due to 31 previous errors

Some errors occurred: E0277, E0599, E0605, E0609.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `rusticata`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rusticata src/lib.rs --crate-type dylib --emit=dep-info,link -C debuginfo=2 -C metadata=12a6adecd0294fff --out-dir /root/rustica/rusticata/target/debug/deps -C incremental=/root/rustica/rusticata/target/debug/incremental -L dependency=/root/rustica/rusticata/target/debug/deps --extern enum_primitive=/root/rustica/rusticata/target/debug/deps/libenum_primitive-bd971dfc38bff4ba.rlib --extern ipsec_parser=/root/rustica/rusticata/target/debug/deps/libipsec_parser-7750cba75212612c.rlib --extern libc=/root/rustica/rusticata/target/debug/deps/liblibc-40d568469a8c2e87.rlib --extern log=/root/rustica/rusticata/target/debug/deps/liblog-53aa957b498c051c.rlib --extern nom=/root/rustica/rusticata/target/debug/deps/libnom-75bc6eea65c5565d.rlib --extern ntp_parser=/root/rustica/rusticata/target/debug/deps/libntp_parser-4b4685e071c364a2.rlib --extern num_traits=/root/rustica/rusticata/target/debug/deps/libnum_traits-39b064a77a137b26.rlib --extern ssh_parser=/root/rustica/rusticata/target/debug/deps/libssh_parser-550406b7607f8e46.rlib --extern tls_parser=/root/rustica/rusticata/target/debug/deps/libtls_parser-374bdc3fc69cb2b2.rlib` (exit code: 1)

**Comment by chifflier** [comment]
This seems to be a problem in dependencies, I think both nom 3 and 4 are included. You can check that by running `grep nom Cargo.lock`.
Edit: this is https://github.com/rusticata/rusticata/issues/4

**Comment by chifflier** [comment]
Fixed by https://github.com/rusticata/openvpn-parser/commit/fb63ff8b01de4a1bf6477645141c0561c5e6635d in openvpn-parser
